import { ArrowDown, Copy, Download, GripVertical, Plus, Trash2, X, Zap } from "lucide-react";
import { useCallback, useRef, useState } from "react";

export interface ChainGadget {
  id: string;
  addr: number;
  insns: string[];
  note?: string;
  value?: string; // optional value placed after gadget (e.g. pop rdi; ret → "/bin/sh addr")
}

export interface ROPChainBuilderProps {
  availableGadgets?: { addr: number; insns: string[] }[];
}

const DEMO_GADGETS = [
  { addr: 0x401234, insns: ["pop rdi", "ret"] },
  { addr: 0x401238, insns: ["pop rsi", "pop r15", "ret"] },
  { addr: 0x40123c, insns: ["pop rdx", "ret"] },
  { addr: 0x401240, insns: ["pop rax", "ret"] },
  { addr: 0x401244, insns: ["xor edi, edi", "ret"] },
  { addr: 0x401248, insns: ["ret"] },
  { addr: 0x401250, insns: ["syscall"] },
  { addr: 0x401254, insns: ["mov [rdi], rsi", "ret"] },
  { addr: 0x401260, insns: ["add rsp, 0x10", "ret"] },
];

function addr(n: number) {
  return `0x${n.toString(16).padStart(16, "0")}`;
}

function exportChain(chain: ChainGadget[], baseOffset = 0): string {
  const lines = [
    "from pwn import *",
    "",
    "# ── ROP Chain ──────────────────────────────────────────────────────────────",
    `# Generated by NullForge — ${chain.length} gadgets`,
    "",
    "rop = b''",
  ];
  for (const g of chain) {
    const comment = g.note ? `  # ${g.note}` : `  # ${g.insns.join("; ")}`;
    lines.push(`rop += p64(0x${(g.addr + baseOffset).toString(16)})${comment}`);
    if (g.value) {
      const cleaned = g.value.trim();
      if (cleaned.startsWith("0x") || /^\d+$/.test(cleaned)) {
        lines.push(`rop += p64(${cleaned})  # value`);
      } else {
        lines.push(`rop += p64(${cleaned})  # ${cleaned}`);
      }
    }
  }
  lines.push("", "# Total size: 0x{:x} bytes".replace("{:x}", (chain.length * 8).toString(16)));
  return lines.join("\n");
}

function exportChainC(chain: ChainGadget[], baseOffset = 0): string {
  const lines = [
    "/* ROP Chain — NullForge */",
    `size_t chain[] = {`,
  ];
  for (const g of chain) {
    const comment = `/* ${g.insns.join("; ")}${g.note ? " | " + g.note : ""} */`;
    lines.push(`    0x${(g.addr + baseOffset).toString(16)}UL, ${comment}`);
    if (g.value) {
      lines.push(`    ${g.value}UL, /* value */`);
    }
  }
  lines.push("};");
  return lines.join("\n");
}

function GadgetCard({
  gadget,
  index,
  onRemove,
  onNoteChange,
  onValueChange,
  onMoveUp,
  onMoveDown,
  isFirst,
  isLast,
}: {
  gadget: ChainGadget;
  index: number;
  onRemove: () => void;
  onNoteChange: (note: string) => void;
  onValueChange: (value: string) => void;
  onMoveUp: () => void;
  onMoveDown: () => void;
  isFirst: boolean;
  isLast: boolean;
}) {
  const [editNote, setEditNote] = useState(false);
  const hasPopValue = gadget.insns.some((i) => i.toLowerCase().startsWith("pop") || i.toLowerCase().startsWith("mov") || i.toLowerCase().startsWith("ldr"));

  return (
    <div className="group rounded border border-border bg-surface">
      <div className="flex items-center gap-2 px-2 py-1.5">
        {/* Drag handle (visual only) */}
        <GripVertical size={11} className="text-text-dim flex-shrink-0 cursor-grab" />

        {/* Index */}
        <span className="text-text-dim w-5 text-[10px] flex-shrink-0">{index + 1}</span>

        {/* Address */}
        <span className="font-mono text-xs text-accent-red flex-shrink-0 w-36">{addr(gadget.addr)}</span>

        {/* Instructions */}
        <span className="flex-1 font-mono text-xs text-text-primary truncate">
          {gadget.insns.join("; ")}
        </span>

        {/* Note badge */}
        {gadget.note && !editNote && (
          <span
            onClick={() => setEditNote(true)}
            className="text-[10px] text-blue-400 border border-blue-400/30 px-1.5 rounded cursor-pointer hover:bg-blue-400/10 max-w-[80px] truncate flex-shrink-0"
          >
            {gadget.note}
          </span>
        )}

        {/* Actions */}
        <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0">
          <button
            onClick={onMoveUp}
            disabled={isFirst}
            className="p-0.5 text-text-dim hover:text-text-primary disabled:opacity-30"
            title="Move up"
          >↑</button>
          <button
            onClick={onMoveDown}
            disabled={isLast}
            className="p-0.5 text-text-dim hover:text-text-primary disabled:opacity-30"
            title="Move down"
          >↓</button>
          <button
            onClick={() => setEditNote((v) => !v)}
            className="p-0.5 text-text-dim hover:text-blue-400"
            title="Add note"
          >✎</button>
          <button onClick={onRemove} className="p-0.5 text-text-dim hover:text-accent-red">
            <X size={11} />
          </button>
        </div>
      </div>

      {/* Value field for pop/load gadgets */}
      {hasPopValue && (
        <div className="flex items-center gap-1 px-2 pb-1.5 pl-[60px]">
          <span className="text-text-dim text-[10px] w-10 flex-shrink-0">value:</span>
          <input
            value={gadget.value ?? ""}
            onChange={(e) => onValueChange(e.target.value)}
            placeholder="e.g. 0x401234 or binsh_addr"
            className="flex-1 bg-bg-base border border-border rounded px-1.5 py-0.5 text-[10px] font-mono text-text-primary focus:outline-none focus:border-accent-red"
          />
        </div>
      )}

      {/* Note editor */}
      {editNote && (
        <div className="flex items-center gap-1 px-2 pb-1.5 pl-[60px]">
          <input
            value={gadget.note ?? ""}
            onChange={(e) => onNoteChange(e.target.value)}
            onBlur={() => setEditNote(false)}
            onKeyDown={(e) => { if (e.key === "Enter" || e.key === "Escape") setEditNote(false); }}
            placeholder="Add note..."
            autoFocus
            className="flex-1 bg-bg-base border border-border rounded px-1.5 py-0.5 text-[10px] text-text-primary focus:outline-none focus:border-accent-red"
          />
        </div>
      )}
    </div>
  );
}

export function ROPChainBuilder({ availableGadgets = DEMO_GADGETS }: ROPChainBuilderProps) {
  const [chain, setChain] = useState<ChainGadget[]>([]);
  const [showPicker, setShowPicker] = useState(false);
  const [pickerQuery, setPickerQuery] = useState("");
  const [baseOffset, setBaseOffset] = useState("0");
  const [exportFormat, setExportFormat] = useState<"python" | "c">("python");
  const [showExport, setShowExport] = useState(false);

  const pickerInputRef = useRef<HTMLInputElement>(null);

  const addGadget = useCallback((g: { addr: number; insns: string[] }) => {
    const entry: ChainGadget = {
      id: `gadget-${Date.now()}-${Math.random()}`,
      addr: g.addr,
      insns: g.insns,
    };
    setChain((c) => [...c, entry]);
  }, []);

  const removeGadget = useCallback((id: string) => {
    setChain((c) => c.filter((g) => g.id !== id));
  }, []);

  const updateNote = useCallback((id: string, note: string) => {
    setChain((c) => c.map((g) => g.id === id ? { ...g, note: note || undefined } : g));
  }, []);

  const updateValue = useCallback((id: string, value: string) => {
    setChain((c) => c.map((g) => g.id === id ? { ...g, value: value || undefined } : g));
  }, []);

  const moveUp = useCallback((idx: number) => {
    if (idx === 0) return;
    setChain((c) => {
      const n = [...c];
      [n[idx - 1], n[idx]] = [n[idx], n[idx - 1]];
      return n;
    });
  }, []);

  const moveDown = useCallback((idx: number) => {
    setChain((c) => {
      if (idx >= c.length - 1) return c;
      const n = [...c];
      [n[idx], n[idx + 1]] = [n[idx + 1], n[idx]];
      return n;
    });
  }, []);

  const filtered = availableGadgets.filter((g) => {
    if (!pickerQuery) return true;
    const q = pickerQuery.toLowerCase();
    return g.insns.join(" ").toLowerCase().includes(q) || g.addr.toString(16).includes(q);
  });

  const offset = parseInt(baseOffset, 16) || 0;
  const exportCode = exportFormat === "python" ? exportChain(chain, offset) : exportChainC(chain, offset);

  return (
    <div className="flex flex-col h-full bg-bg-base text-xs">
      {/* Toolbar */}
      <div className="flex items-center gap-2 px-2 py-1.5 border-b border-border bg-surface flex-shrink-0 flex-wrap">
        <span className="font-medium text-text-muted">Chain Builder</span>
        <span className="text-text-dim">{chain.length} gadget{chain.length !== 1 ? "s" : ""}</span>
        <div className="flex items-center gap-1 ml-auto">
          <span className="text-text-dim">base:</span>
          <input
            value={baseOffset}
            onChange={(e) => setBaseOffset(e.target.value)}
            className="w-28 bg-bg-base border border-border rounded px-1.5 py-0.5 text-[10px] font-mono text-text-primary focus:outline-none focus:border-accent-red"
          />
          <button
            onClick={() => { setShowPicker((v) => !v); setTimeout(() => pickerInputRef.current?.focus(), 50); }}
            className="flex items-center gap-1 px-2 py-1 rounded bg-accent-red text-white text-[10px] hover:bg-accent-red/80 transition-colors"
          >
            <Plus size={10} /> Gadget
          </button>
          {chain.length > 0 && (
            <button
              onClick={() => setShowExport((v) => !v)}
              className="flex items-center gap-1 px-2 py-1 rounded bg-elevated border border-border text-text-muted hover:text-text-primary text-[10px] transition-colors"
            >
              <Download size={10} /> Export
            </button>
          )}
          {chain.length > 0 && (
            <button
              onClick={() => setChain([])}
              className="p-1 text-text-dim hover:text-accent-red transition-colors"
              title="Clear chain"
            >
              <Trash2 size={12} />
            </button>
          )}
        </div>
      </div>

      {/* Gadget picker */}
      {showPicker && (
        <div className="border-b border-border bg-elevated flex-shrink-0">
          <div className="px-2 pt-1.5 pb-1">
            <input
              ref={pickerInputRef}
              value={pickerQuery}
              onChange={(e) => setPickerQuery(e.target.value)}
              placeholder="Search gadgets..."
              className="w-full bg-bg-base border border-border rounded px-2 py-1 text-[10px] font-mono text-text-primary focus:outline-none focus:border-accent-red"
            />
          </div>
          <div className="max-h-36 overflow-y-auto">
            {filtered.slice(0, 80).map((g, i) => (
              <button
                key={i}
                onClick={() => { addGadget(g); setPickerQuery(""); }}
                className="w-full flex items-center gap-2 px-3 py-1 hover:bg-surface text-left transition-colors"
              >
                <span className="font-mono text-[10px] text-text-dim w-28 flex-shrink-0">0x{g.addr.toString(16)}</span>
                <span className="font-mono text-[10px] text-text-primary flex-1">{g.insns.join("; ")}</span>
                <Plus size={10} className="text-text-dim flex-shrink-0" />
              </button>
            ))}
            {filtered.length === 0 && (
              <div className="px-3 py-2 text-text-dim text-[10px]">No gadgets match</div>
            )}
          </div>
        </div>
      )}

      {/* Export view */}
      {showExport && chain.length > 0 && (
        <div className="border-b border-border bg-surface flex-shrink-0 p-2 space-y-1">
          <div className="flex items-center gap-2">
            {(["python", "c"] as const).map((f) => (
              <button
                key={f}
                onClick={() => setExportFormat(f)}
                className={`px-2 py-0.5 rounded text-[10px] uppercase ${
                  exportFormat === f ? "bg-accent-red text-white" : "bg-elevated border border-border text-text-muted"
                }`}
              >
                {f}
              </button>
            ))}
            <button
              onClick={() => navigator.clipboard.writeText(exportCode).catch(() => {})}
              className="ml-auto flex items-center gap-1 px-2 py-0.5 rounded bg-elevated border border-border text-text-muted hover:text-text-primary text-[10px]"
            >
              <Copy size={10} /> Copy
            </button>
          </div>
          <pre className="bg-bg-base border border-border rounded px-2 py-1.5 text-[10px] font-mono text-text-primary overflow-x-auto max-h-40">{exportCode}</pre>
        </div>
      )}

      {/* Chain list */}
      <div className="flex-1 overflow-y-auto p-2 space-y-1">
        {chain.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full gap-2 text-text-dim">
            <Zap size={20} className="opacity-30" />
            <p className="text-[11px]">Chain is empty. Click + Gadget to start building.</p>
          </div>
        ) : (
          chain.map((g, i) => (
            <div key={g.id}>
              <GadgetCard
                gadget={g}
                index={i}
                onRemove={() => removeGadget(g.id)}
                onNoteChange={(note) => updateNote(g.id, note)}
                onValueChange={(value) => updateValue(g.id, value)}
                onMoveUp={() => moveUp(i)}
                onMoveDown={() => moveDown(i)}
                isFirst={i === 0}
                isLast={i === chain.length - 1}
              />
              {i < chain.length - 1 && (
                <div className="flex justify-center py-0.5 text-text-dim">
                  <ArrowDown size={10} />
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* Footer: size info */}
      {chain.length > 0 && (
        <div className="flex items-center gap-3 px-3 py-1 border-t border-border bg-surface flex-shrink-0 text-[10px] text-text-dim">
          <span>Size: 0x{(chain.length * 8).toString(16)} bytes ({chain.length * 8} b)</span>
          <span>Gadgets: {chain.length}</span>
          <span>Values: {chain.filter((g) => g.value).length}</span>
        </div>
      )}
    </div>
  );
}
