import type * as Monaco from "monaco-editor";

export function registerNullForgeTheme(monaco: typeof Monaco) {
  monaco.editor.defineTheme("nullforge-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "475569", fontStyle: "italic" },
      { token: "keyword", foreground: "38bdf8", fontStyle: "bold" },
      { token: "keyword.control", foreground: "c084fc" },
      { token: "type", foreground: "fbbf24" },
      { token: "type.identifier", foreground: "4ade80", fontStyle: "bold" },
      { token: "number", foreground: "fb923c" },
      { token: "number.hex", foreground: "f97316" },
      { token: "string", foreground: "a3e635" },
      { token: "variable", foreground: "e63946", fontStyle: "bold" },    // registers
      { token: "identifier", foreground: "e2e8f0" },
      { token: "operators", foreground: "94a3b8" },
      { token: "delimiter", foreground: "64748b" },
      { token: "delimiter.bracket", foreground: "94a3b8" },
      { token: "delimiter.curly", foreground: "94a3b8" },
      { token: "delimiter.parenthesis", foreground: "94a3b8" },
      // Python
      { token: "keyword.python", foreground: "38bdf8" },
      { token: "string.python", foreground: "a3e635" },
      // C/C++
      { token: "keyword.cpp", foreground: "38bdf8" },
      { token: "preprocessor.cpp", foreground: "c084fc" },
    ],
    colors: {
      "editor.background": "#0d0f14",
      "editor.foreground": "#e2e8f0",
      "editor.lineHighlightBackground": "#141720",
      "editor.lineHighlightBorder": "#1e2330",
      "editor.selectionBackground": "#1e4070",
      "editor.selectionHighlightBackground": "#1e3050",
      "editor.inactiveSelectionBackground": "#162035",
      "editor.findMatchBackground": "#e6394640",
      "editor.findMatchHighlightBackground": "#e6394625",
      "editorLineNumber.foreground": "#3d4a5c",
      "editorLineNumber.activeForeground": "#64748b",
      "editorCursor.foreground": "#e63946",
      "editorWhitespace.foreground": "#1e2330",
      "editorIndentGuide.background1": "#1e2330",
      "editorIndentGuide.activeBackground1": "#2d3748",
      "editorGutter.background": "#0d0f14",
      "editorWidget.background": "#141720",
      "editorWidget.border": "#1e2330",
      "editorSuggestWidget.background": "#141720",
      "editorSuggestWidget.border": "#1e2330",
      "editorSuggestWidget.selectedBackground": "#1e2d40",
      "editorSuggestWidget.highlightForeground": "#e63946",
      "editorHoverWidget.background": "#141720",
      "editorHoverWidget.border": "#1e2330",
      "input.background": "#0d0f14",
      "input.border": "#1e2330",
      "input.foreground": "#e2e8f0",
      "input.placeholderForeground": "#475569",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#1e233066",
      "scrollbarSlider.hoverBackground": "#2d374899",
      "scrollbarSlider.activeBackground": "#38bdf833",
      "minimap.background": "#0d0f14",
      "breadcrumb.background": "#0d0f14",
      "breadcrumb.foreground": "#64748b",
      "breadcrumb.activeSelectionForeground": "#e2e8f0",
      "tab.activeBackground": "#0d0f14",
      "tab.inactiveBackground": "#141720",
      "tab.activeBorder": "#e63946",
      "tab.border": "#1e2330",
      "editorGroupHeader.tabsBackground": "#141720",
    },
  });
}
